# Generated by Django 5.1.2 on 2024-10-08 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AddField(
            model_name='livro',
            name='publicado_em',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
