# Generated by Django 5.1.2 on 2024-11-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autor_biografia_alter_livro_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
