# Generated by Django 5.1.2 on 2024-11-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livro_imagem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='imagem_url',
        ),
    ]
